name: geometry_kp
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/dlmauri/geometry
author: maurizio dell'oso <dellosomaurizio@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
